# [START gae_python37_cloudsql_config]
runtime: python310

entrypoint: gunicorn -b :$PORT app:app  # Adjust app:app if needed

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 
  CLOUD_SQL_DATABASE_NAME: users_db
  CLOUD_SQL_CONNECTION_NAME: localhost
# [END gae_python37_cloudsql_config]

# Handlers for static content
handlers:
  - url: /static
    static_dir: static

  - url: /knowledge_base.json
    static_files: knowledge_base.json
    upload: knowledge_base.json
