runtime: python39

entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /static
    static_dir: static

  - url: /knowledge_base.json
    static_files: knowledge_base.json
    upload: knowledge_base.json

  - url: /.*
    script: auto